### ISSUE TITLE
Docker file enhancements

### ISSUE THREAD

**Issue by cjus** [flywheelsports/generator-fwsp-hydra#12]
In the generated Docker file:

* Thinking that the maintainer name/email should be changed to: `Your name name@yourdomain.com`
* We should use mount points for the config folder... that would allow for updating services without having to commit changes to a container.  See: https://docs.docker.com/engine/reference/builder/#volume

**Comment by cjus** [comment]
Perhaps there should be a generator props for organization and user name an email address.
Then the docker namespace and maintainer can be properly set in the resulting `scripts/docker.js` file.

**Comment by cjus** [comment]
The generated Dockerfile should use `RUN npm install --production` to ensure that devDependencies don't make it into the created container.

**Comment by emadum** [comment]
> We should use mount points for the config folder... that would allow for updating services without having to commit changes to a container. See: https://docs.docker.com/engine/reference/builder/#volume

I can see that being useful, but I'm not sure it makes sense as a default. What would the volume name be?
