### ISSUE TITLE
Remove Newline format for routes?

### ISSUE THREAD

**Issue by cjus** [flywheelsports/generator-fwsp-hydra#17]
In the generated {service}-v1.route.js file the (req, res) appears on a new line.

```javascript
api.get('/', hydraExpress.validateJwtToken(),
(req, res) => {
  res.sendOk({greeting: 'Welcome to Hydra Express!'});
});
```

Can you change it to:

```javascript
api.get('/', hydraExpress.validateJwtToken(), (req, res) => {
  res.sendOk({greeting: 'Welcome to Hydra Express!'});
});
```

I think I prefer the format above. But if you're attached to it let's discuss ;-)

**Comment by emadum** [comment]
I like having it on a new line, particularly when there's a lot of middleware it's a lot easier to read. We may no longer be in the age of 80 char lines, but some of the route definitions end up well over 200 chars, which looks pretty unsightly to me.
