### ISSUE TITLE
Error: spawn npm ENOENT

### ISSUE THREAD

**Issue by marcan2020** [flywheelsports/generator-fwsp-hydra#22]
I'm using Windows 10 64 bits and whenever I try to generate an hydra template I get this error:

![image](https://cloud.githubusercontent.com/assets/15129756/22620816/c7f9f9da-eae1-11e6-9e54-49bb96e54214.png)

Note: I can use other generators with yo and they are working fine.

**Comment by cjus** [comment]
@marcan2020 thanks for heads up. We'll get back to you shortly. @emadum do you have access to a Windows box?

**Comment by emadum** [comment]
Looks like this is the problem:
https://github.com/nodejs/node/issues/3675

I'll test it out on a Win10 machine and get a fix deployed.
