### ISSUE TITLE
Default to node:alpine in scripts/docker.js

### ISSUE THREAD

**Issue by ecwyne** [flywheelsports/generator-fwsp-hydra#24]
https://github.com/flywheelsports/generator-fwsp-hydra/blob/master/app/templates/scripts/docker.js#L11

I have only ever had one docker image that I wasn't able to run using the `node:alpine` image. (see [docs](https://github.com/nodejs/docker-node#nodealpine)). I believe that using the (much smaller) `alpine` image would be a sane default for new hydra services. A `docker.md` can be created detailing how to use `scripts/docker.js` as well as how to switch to the "full" `node` image when necessary.

Before I created a PR I wanted to get feedback about whether or not this would make sense and any other considerations I would need to keep in mind for a PR.

**Comment by cjus** [comment]
One issue we encountered is that use of Alpine can lead to issues building services which depend on system libraries which may not be present on a stripped down Linux.  So it's safer to choose a base image that is larger and more complete by way of libraries. The user can always experiment with other base images. The goal of the generator (and @emadum can speak to this) is to create a project head start which can be later customized by the developer.

**Comment by emadum** [comment]
Yeah, I went with the Debian image for convenience while developing services; it's often useful to attach to the container and apt-get install a few things, and the package manager in alpine isn't nearly as comprehensive. Perhaps there should be a prompt in the generator giving some more options including `node:alpine`?

**Comment by ecwyne** [comment]
Thanks @cjus!

>The main caveat to note is that it does use musl libc instead of glibc and friends, so certain software might run into issues depending on the depth of their libc requirements. However, most software doesn't have an issue with this, so __this variant is usually a very safe choice__.

This does seem to come down to a matter of preference for the default behavior, balancing speed & developer experience against completeness. Just wanted to share my two cents and hear if there were other opinions. If the consensus is that the default ought to work for 100% of projects then I'm happy to close this issue.

**Comment by ecwyne** [comment]
@emadum I also thought that we could add a prompt to switch between the two, but wasn't sure how to articulate the prompt when the user may not understand what the different options would mean

**Comment by ecwyne** [comment]
> Does this service require the glibc library to build? (Yn)

> Can this service run on the smaller node:alpine image? (yN)

**Comment by cjus** [comment]
The specific issue I encountered was with the uws package for websocket support. I do believe the default generator settings should be the safest for the end user while override option could offer less safe choices.

**Comment by cjus** [comment]
Another issue is that the more questions the generator asks and the more complicated the worded choiced - the worse that is for new users. It would be ideal to have a "need advanced choices" question and then ask a series of advanced questions.
