### ISSUE TITLE
ES6 error

### ISSUE THREAD

**Issue by jchiellini** [flywheelsports/generator-fwsp-hydra#25]
Hello,

I have just started to work my way through this [tutorial](https://community.risingstack.com/deploying-node-js-microservices-to-aws-using-docker/). It begins with installing this yeoman generator to create a microservice. However, it appears that there is a spread operator used in the 'hydra-express' index.js on line 74. When I run 'npm start', it errors out with an "unexpected token ...". 

Is there a quick fix to get this working? Trying to avoid doctoring my own copy of the dependency. But was also wondering if anyone else has seen this issue.

Thank you.

**Comment by emadum** [comment]
What's your node version? `node --version` Hydra [requires at least 6.2.1](https://github.com/flywheelsports/hydra-express/blob/master/package.json#L13).

**Comment by jchiellini** [comment]
Haha sorry about this. I just updated my node version and saw that it worked. Just was running back to this issue and delete my post.
