### ISSUE TITLE
Error: Unhandled "error" event

### ISSUE THREAD

**Issue by tolik93** [flywheelsports/generator-fwsp-hydra#26]
hello. 
I cannot start using hydra clearly. I have following issue

![image](https://user-images.githubusercontent.com/17907942/28056521-6fe8fb3a-661d-11e7-9f9e-f5d7528e32fd.png)

Do you have any idea, how to solve this problem?

**Comment by emadum** [comment]
@tolik93 Apologies for the very delayed response, the issue here was yeoman's API changed significantly in the upgrade to 2.0.

The workaround for this is to target 1.x with your npm install of yo - e.g. `npm -g i yo@^1`
