### ISSUE TITLE
yo fwsp-hydra hello: Unhandled 'error' event

### ISSUE THREAD

**Issue by koolb** [flywheelsports/generator-fwsp-hydra#27]
events.js:189
    throw err; // Unhandled 'error' event
Error [ERR_UNHANDLED_ERROR]: Unhandled error. (<Buffer 6e 70 6d 20 69 6e 66 6f 20 69 74 20 77 6f 72 6b 65 64 20 69 66 20 69 74 20 65 6e 64 73 20 77 69 74 68 20 6f 6b 0a 6e 70 6d 20 76 65 72 62 20 63 6c 69 ... >)
    at child.emit (events.js:187:17)
    at Immediate.<anonymous> (C:\dev\npm\node_modules\generator-fwsp-hydra\app\node_modules\yeoman-generator\lib\base.js:446:16)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

**Comment by emadum** [comment]
Hi @koolb, thanks for the bug report. I haven't checked on this project in a while, but will investigate this issue tonight.

**Comment by koolb** [comment]
Ok so here's more detail two exact same node versions but different OS:
My node is 10.16.0 and the corresponding npm 6.9.0.  Both downloaded today.
 
ubuntu Linux (4.18.0-25-generic x86_64) is fine, ie I can generate a service with yo fwsp_hydra no execptions no errors on Linux.

The issue happens only on windows, in my cygwin, git-bash and powershell cli's on windows 10 using the same node/npm version and install commands. It's instant as soon as you try to gen a service.

I installed both of these as npm -g i yo generator-fwsp-hydra

Thank you for looking.



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by emadum** [comment]
@koolb 

The problem is yeoman introduced some breaking changes in the 2.x upgrade. I don't have time to upgrade this package right now for the latest version of yeoman, but there's a simple workaround which should work - just target yo version 1.x in your npm install. E.g.

`npm -g i yo@^1 generator-fwsp-hydra`

I'll update the docs to reduce confusion. Thanks!

**Comment by koolb** [comment]
Sent from my Samsung Galaxy smartphone.

-------- Original message --------

**Comment by koolb** [comment]
This still has same error on windows using yo 1.85. fyi.
